import http from 'http';
import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';

const PORT = process.env.PORT || 5174;
const root = path.resolve('.');
const GENERATED_DIR = path.join(root, 'generated');
const GENERATED_ASSETS_DIR = path.join(GENERATED_DIR, 'assets');

const mime = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
};

function safeJoin(rootDir, urlPath) {
  const normalized = path.normalize(path.join(rootDir, urlPath));
  if (!normalized.startsWith(rootDir)) return null;
  return normalized;
}

function sendFile(fp, res) {
  const ext = path.extname(fp).toLowerCase();
  const ct = mime[ext] || 'application/octet-stream';
  res.writeHead(200, { 'Content-Type': ct, 'Cache-Control': 'no-cache' });
  const stream = fs.createReadStream(fp);
  stream.pipe(res);
  stream.on('error', () => { res.writeHead(500); res.end('Read error'); });
}

// Ensure generated assets dir exists
fs.mkdirSync(GENERATED_ASSETS_DIR, { recursive: true });

const INDEX_HTML = `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Story.report - UI</title>
<style>body{font-family:Arial,Helvetica,sans-serif;margin:18px;background:#0b0b0b;color:#eee}label{display:block;margin-top:8px;font-size:13px}input,select,button{padding:8px;margin-top:6px;border-radius:6px;border:1px solid #444;background:#111;color:#eee}#preview{margin-top:18px;max-width:480px}</style>
</head><body>
<h2>Story.report - UI</h2>
<div>
  <label>Font
    <select id="font"><option>Segoe UI</option><option>Inter</option><option>DM Sans</option><option>IBM Plex Mono</option></select>
  </label>
  <label>Background color
    <input id="bg" type="color" value="#0f0f0f" />
  </label>
  <label>Accent color
    <input id="accent" type="color" value="#e8d5a3" />
  </label>
  <label>Date from
    <input id="from" type="date" />
  </label>
  <label>Date to
    <input id="to" type="date" />
  </label>
  <label>Footer text
    <input id="footer" type="text" placeholder="Generated by Story.report" />
  </label>
  <div style="margin-top:12px">
    <button id="gen">Generate report</button>
    <span id="status" style="margin-left:12px"></span>
  </div>
  <div id="preview"></div>
  <div id="imgwrap" style="margin-top:12px"></div>
</div>
<script>
document.getElementById('gen').addEventListener('click', async ()=>{
  const font=document.getElementById('font').value;
  const bg=document.getElementById('bg').value;
  const accent=document.getElementById('accent').value;
  const from=document.getElementById('from').value||null;
  const to=document.getElementById('to').value||null;
  const footer=document.getElementById('footer').value||null;
  document.getElementById('status').textContent='Generating...';

  // request generation
  const payload = { font, bg, accent, from, to, footer };
  const gen = await fetch('/api/generate', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
  const result = await gen.json();
  document.getElementById('status').textContent = result.ok ? 'Done' : ('Error: '+(result.error||''));
  if (result.ok) {
    const imgwrap=document.getElementById('imgwrap'); imgwrap.innerHTML='';
    const img=document.createElement('img'); img.src='/generated/report.png?ts='+Date.now(); img.style.maxWidth='360px'; img.style.borderRadius='8px'; imgwrap.appendChild(img);
  }
});
</script>
</body></html>`;

const server = http.createServer(async (req, res) => {
  try {
    const urlPath = decodeURIComponent(req.url.split('?')[0]);

    if (req.method === 'GET' && (urlPath === '/' || urlPath === '')) {
      res.writeHead(200, {'Content-Type':'text/html; charset=utf-8'});
      res.end(INDEX_HTML);
      return;
    }

    // Serve generated files under /generated
    if (req.method === 'GET' && urlPath.startsWith('/generated/')) {
      const filePath = safeJoin(root, urlPath);
      if (!filePath) { res.writeHead(403); res.end('Forbidden'); return; }
      try { await fs.promises.access(filePath); sendFile(filePath, res); } catch { res.writeHead(404); res.end('Not found'); }
      return;
    }

    // avatar upload endpoint removed

    // Trigger generation
    if (req.method === 'POST' && urlPath === '/api/generate') {
      let body=''; for await (const chunk of req) body+=chunk;
      try {
        const cfg = JSON.parse(body);

        // Build environment for child process
        const env = Object.assign({}, process.env);
        if (cfg.font) env.REPORT_FONT = cfg.font;
        if (cfg.bg) env.REPORT_BG = cfg.bg;
        if (cfg.accent) env.REPORT_ACCENT = cfg.accent;
        if (cfg.footer) env.REPORT_FOOTER_TEXT = cfg.footer;
        if (cfg.from) env.REPORT_DATE_FROM = cfg.from;
        if (cfg.to) env.REPORT_DATE_TO = cfg.to;

        // Spawn index.js with --force to produce fresh output
        const child = spawn(process.execPath, [path.join(root,'index.js'), '--force'], { env, cwd: root });
        let stdout = '', stderr = '';
        child.stdout.on('data', d => { stdout += d.toString(); });
        child.stderr.on('data', d => { stderr += d.toString(); });
        child.on('close', code => {
          if (code === 0) {
            res.writeHead(200, {'Content-Type':'application/json'});
            res.end(JSON.stringify({ok:true}));
          } else {
            res.writeHead(500, {'Content-Type':'application/json'});
            res.end(JSON.stringify({ok:false,error:stderr||stdout||('exit '+code)}));
          }
        });
      } catch (e) { res.writeHead(500,{'Content-Type':'application/json'}); res.end(JSON.stringify({ok:false,error:e.message})); }
      return;
    }

    // Fallback: not found
    res.writeHead(404);
    res.end('Not found');
  } catch (err) {
    res.writeHead(500);
    res.end('Server error');
  }
});

server.listen(PORT, () => console.log(`UI server running: http://localhost:${PORT}/`));
