import { useState } from 'react';

export default function Home() {
  const [font, setFont] = useState('Segoe UI');
  const [bg, setBg] = useState('#0f0f0f');
  const [accent, setAccent] = useState('#e8d5a3');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [footer, setFooter] = useState('Generated by Story.report');
  const [status, setStatus] = useState('');
  const [imageUrl, setImageUrl] = useState(null);
  const [imageVersion, setImageVersion] = useState(0);

  async function generate() {
    setStatus('Generating...');
    setImageUrl(null);
    try {
      const resp = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ font, bg, accent, from, to, footer }),
      });
      const data = await resp.json();
      if (data.ok) {
        setStatus('Done');
        const version = Date.now();
        setImageVersion(version);
        setImageUrl('/api/report-image?ts=' + version);
      } else {
        setStatus('Error: ' + (data.error || 'unknown'));
      }
    } catch (err) {
      setStatus('Error: ' + err.message);
    }
  }

  return (
    <div style={{ padding: 24, fontFamily: 'Arial, Helvetica, sans-serif', background: '#0b0b0b', color: '#eee' }}>
      <h1>Story.report - Web UI</h1>

      <label style={{ display: 'block', marginTop: 8 }}>Font
        <select value={font} onChange={(e) => setFont(e.target.value)} style={{ marginLeft: 8 }}>
          <option>Segoe UI</option>
          <option value="mono">Mono preset</option>
          <option value="serif">Serif preset</option>
          <option>Consolas</option>
          <option>Courier New</option>
        </select>
      </label>

      <label style={{ display: 'block', marginTop: 8 }}>Background color
        <input type="color" value={bg} onChange={(e) => setBg(e.target.value)} style={{ marginLeft: 8 }} />
      </label>

      <label style={{ display: 'block', marginTop: 8 }}>Accent color
        <input type="color" value={accent} onChange={(e) => setAccent(e.target.value)} style={{ marginLeft: 8 }} />
      </label>

      <label style={{ display: 'block', marginTop: 8 }}>Date from
        <input type="date" value={from} onChange={(e) => setFrom(e.target.value)} style={{ marginLeft: 8 }} />
      </label>

      <label style={{ display: 'block', marginTop: 8 }}>Date to
        <input type="date" value={to} onChange={(e) => setTo(e.target.value)} style={{ marginLeft: 8 }} />
      </label>

      <label style={{ display: 'block', marginTop: 8 }}>Footer text
        <input type="text" value={footer} onChange={(e) => setFooter(e.target.value)} style={{ marginLeft: 8 }} />
      </label>

      <div style={{ marginTop: 12 }}>
        <button onClick={generate} style={{ padding: 8, borderRadius: 6 }}>Generate report</button>
        <span style={{ marginLeft: 12 }}>{status}</span>
      </div>

      {imageUrl && (
        <div style={{ marginTop: 12 }}>
          <img key={imageVersion} src={imageUrl} alt="report" style={{ maxWidth: 360, borderRadius: 8 }} />
        </div>
      )}
    </div>
  );
}
