import { useState, useEffect, useRef } from 'react';

const FONT_OPTIONS = [
  { value: 'Segoe UI', label: 'Segoe UI' },
  { value: 'mono', label: 'Mono preset' },
  { value: 'serif', label: 'Serif preset' },
  { value: 'Consolas', label: 'Consolas' },
  { value: 'Courier New', label: 'Courier New' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Arial', label: 'Arial' },
  { value: 'Times New Roman', label: 'Times New Roman' },
];

export default function Home() {
  const [font, setFont] = useState('Segoe UI');
  const [bg, setBg] = useState('#0f0f0f');
  const [accent, setAccent] = useState('#e8d5a3');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [footer, setFooter] = useState('Generated by Story.report');
  const [mosaicArtistCount, setMosaicArtistCount] = useState(8);
  const [enableMosaic, setEnableMosaic] = useState(true);
  const [enableStatistics, setEnableStatistics] = useState(true);
  const [enableTopItems, setEnableTopItems] = useState(true);
  const [enableWordCloud, setEnableWordCloud] = useState(true);
  const [textColorMode, setTextColorMode] = useState('auto');
  const [status, setStatus] = useState('');
  const [imageUrl, setImageUrl] = useState(null);
  const [imageVersion, setImageVersion] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const autoGenerateTimeoutRef = useRef(null);

  // Auto-generate on config changes (debounced)
  useEffect(() => {
    // Clear existing timeout
    if (autoGenerateTimeoutRef.current) {
      clearTimeout(autoGenerateTimeoutRef.current);
    }

    // Set new timeout to generate after user stops typing/changing (500ms debounce)
    autoGenerateTimeoutRef.current = setTimeout(() => {
      generateReport(false);
    }, 500);

    return () => {
      if (autoGenerateTimeoutRef.current) {
        clearTimeout(autoGenerateTimeoutRef.current);
      }
    };
  }, [font, bg, accent, from, to, footer, mosaicArtistCount, enableMosaic, enableStatistics, enableTopItems, enableWordCloud, textColorMode]);

  async function generateReport(forceFetch = false) {
    setStatus(forceFetch ? '⏳ Force fetching...' : '⏳ Generating...');
    setImageUrl(null);
    setIsLoading(true);
    try {
      const resp = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ font, bg, accent, from, to, footer, forceFetch, mosaicArtistCount, enableMosaic, enableStatistics, enableTopItems, enableWordCloud, textColorMode }),
      });
      const data = await resp.json();
      if (data.ok) {
        setStatus('✅ Done!');
        const version = Date.now();
        setImageVersion(version);
        setImageUrl('/api/report-image?ts=' + version);
        // Clear status after 2 seconds
        setTimeout(() => setStatus(''), 2000);
      } else {
        setStatus('❌ Error: ' + (data.error || 'unknown'));
      }
    } catch (err) {
      setStatus('❌ Error: ' + err.message);
    } finally {
      setIsLoading(false);
    }
  }

  const containerStyle = {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '32px',
    padding: '24px',
    paddingLeft: 'max(24px, calc((100vw - 1400px) / 2))',
    paddingRight: 'max(24px, calc((100vw - 1400px) / 2))',
    fontFamily: "'Segoe UI', Arial, sans-serif",
    background: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 100%)',
    color: '#eee',
    minHeight: '100vh',
    maxWidth: '1400px',
    margin: '0 auto',
  };

  const formContainerStyle = {
    maxWidth: '500px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  };

  const formStyle = {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  };

  const labelStyle = {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    fontSize: '14px',
    fontWeight: '500',
  };

  const labelTextStyle = {
    color: '#aaa',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    fontSize: '12px',
  };

  const inputStyle = {
    padding: '10px 12px',
    borderRadius: '6px',
    border: '1px solid #333',
    background: '#1a1a1a',
    color: '#eee',
    fontSize: '14px',
    transition: 'all 0.2s ease',
  };

  const selectStyle = {
    ...inputStyle,
    cursor: 'pointer',
  };

  const buttonStyle = {
    padding: '10px 16px',
    borderRadius: '6px',
    border: 'none',
    background: '#e8d5a3',
    color: '#0a0a0a',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'all 0.2s ease',
    whiteSpace: 'nowrap',
  };

  const buttonSecondaryStyle = {
    ...buttonStyle,
    background: '#333',
    color: '#eee',
  };

  const buttonsContainerStyle = {
    display: 'flex',
    gap: '8px',
    flexDirection: 'column',
  };

  const previewContainerStyle = {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    position: 'sticky',
    top: '24px',
    maxHeight: 'calc(100vh - 48px)',
  };

  const previewBoxStyle = {
    background: '#1a1a1a',
    borderRadius: '8px',
    padding: '12px',
    border: '1px solid #333',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    minHeight: '400px',
    overflow: 'auto',
  };

  const statusStyle = {
    fontSize: '14px',
    color: status.includes('Error') ? '#ff6b6b' : status.includes('Done') ? '#a8d5ba' : '#ffd700',
    fontWeight: '500',
    minHeight: '20px',
  };

  const colorInputStyle = {
    ...inputStyle,
    cursor: 'pointer',
    height: '40px',
    padding: '4px',
  };

  return (
    <div style={containerStyle}>
      <div style={formContainerStyle}>
        <h1 style={{ marginTop: 0, marginBottom: '16px', fontSize: '28px', fontWeight: '600' }}>
          📊 Story.report
        </h1>

        <div style={formStyle}>
          {/* Font selection with font preview */}
          <label style={labelStyle}>
            <span style={labelTextStyle}>Font</span>
            <select
              value={font}
              onChange={(e) => setFont(e.target.value)}
              style={{
                ...selectStyle,
                fontFamily: font === 'mono' ? 'Consolas, monospace' : font === 'serif' ? 'Georgia, serif' : font,
              }}
            >
              {FONT_OPTIONS.map((opt) => (
                <option
                  key={opt.value}
                  value={opt.value}
                  style={{
                    fontFamily: opt.value === 'mono' ? 'Consolas, monospace' : opt.value === 'serif' ? 'Georgia, serif' : opt.value,
                  }}
                >
                  {opt.label}
                </option>
              ))}
            </select>
          </label>

          {/* Background color */}
          <label style={labelStyle}>
            <span style={labelTextStyle}>Background Color</span>
            <input type="color" value={bg} onChange={(e) => setBg(e.target.value)} style={colorInputStyle} />
          </label>

          {/* Accent color */}
          <label style={labelStyle}>
            <span style={labelTextStyle}>Accent Color</span>
            <input type="color" value={accent} onChange={(e) => setAccent(e.target.value)} style={colorInputStyle} />
          </label>

          {/* Date range */}
          <label style={labelStyle}>
            <span style={labelTextStyle}>Date From</span>
            <input type="date" value={from} onChange={(e) => setFrom(e.target.value)} style={inputStyle} />
          </label>

          <label style={labelStyle}>
            <span style={labelTextStyle}>Date To</span>
            <input type="date" value={to} onChange={(e) => setTo(e.target.value)} style={inputStyle} />
          </label>

          {/* Mosaic artist count */}
          <label style={labelStyle}>
            <span style={labelTextStyle}>Top Artists Mosaic Count</span>
            <select value={mosaicArtistCount} onChange={(e) => setMosaicArtistCount(parseInt(e.target.value))} style={selectStyle} disabled={!enableMosaic}>
              <option value={8}>8 artists</option>
            </select>
          </label>

          {/* Module toggles */}
          <div style={{ borderTop: '1px solid #333', paddingTop: '12px', marginTop: '12px' }}>
            <span style={labelTextStyle}>Modules</span>

            <label style={{ ...labelStyle, flexDirection: 'row', alignItems: 'center', gap: '8px', marginTop: '8px' }}>
              <input
                type="checkbox"
                checked={enableStatistics}
                onChange={(e) => setEnableStatistics(e.target.checked)}
                style={{ width: '18px', height: '18px', cursor: 'pointer' }}
              />
              <span style={{ ...labelTextStyle, textTransform: 'none', fontSize: '14px' }}>Statistics (artists, albums, tracks)</span>
            </label>

            <label style={{ ...labelStyle, flexDirection: 'row', alignItems: 'center', gap: '8px', marginTop: '8px' }}>
              <input
                type="checkbox"
                checked={enableMosaic}
                onChange={(e) => setEnableMosaic(e.target.checked)}
                style={{ width: '18px', height: '18px', cursor: 'pointer' }}
              />
              <span style={{ ...labelTextStyle, textTransform: 'none', fontSize: '14px' }}>Top Artists Mosaic</span>
            </label>

            <label style={{ ...labelStyle, flexDirection: 'row', alignItems: 'center', gap: '8px', marginTop: '8px' }}>
              <input
                type="checkbox"
                checked={enableTopItems}
                onChange={(e) => setEnableTopItems(e.target.checked)}
                style={{ width: '18px', height: '18px', cursor: 'pointer' }}
              />
              <span style={{ ...labelTextStyle, textTransform: 'none', fontSize: '14px' }}>Top Items (artist, album, track)</span>
            </label>

            <label style={{ ...labelStyle, flexDirection: 'row', alignItems: 'center', gap: '8px', marginTop: '8px' }}>
              <input
                type="checkbox"
                checked={enableWordCloud}
                onChange={(e) => setEnableWordCloud(e.target.checked)}
                style={{ width: '18px', height: '18px', cursor: 'pointer' }}
              />
              <span style={{ ...labelTextStyle, textTransform: 'none', fontSize: '14px' }}>Word Cloud (top tags)</span>
            </label>
          </div>

          {/* Text color mode */}
          <label style={labelStyle}>
            <span style={labelTextStyle}>Text Color Mode</span>
            <select value={textColorMode} onChange={(e) => setTextColorMode(e.target.value)} style={selectStyle}>
              <option value="auto">Auto (based on background)</option>
              <option value="light">Light (white text)</option>
              <option value="dark">Dark (black text)</option>
            </select>
          </label>

          {/* Footer text with clear option */}
          <label style={labelStyle}>
            <span style={labelTextStyle}>Footer Text</span>
            <div style={{ display: 'flex', gap: '8px' }}>
              <input
                type="text"
                value={footer}
                onChange={(e) => setFooter(e.target.value)}
                style={{ ...inputStyle, flex: 1 }}
                placeholder="Leave empty for no footer"
              />
              <button
                onClick={() => setFooter('')}
                style={{
                  padding: '10px 12px',
                  borderRadius: '6px',
                  border: '1px solid #333',
                  background: '#2a2a2a',
                  color: '#aaa',
                  cursor: 'pointer',
                  fontSize: '12px',
                  fontWeight: '600',
                }}
                title="Clear footer text"
              >
                ✕
              </button>
            </div>
          </label>

          {/* Force Fetch button */}
          <button
            onClick={() => generateReport(true)}
            style={buttonSecondaryStyle}
            disabled={isLoading}
            onMouseOver={(e) => !isLoading && (e.target.style.background = '#404040')}
            onMouseOut={(e) => (e.target.style.background = '#333')}
            title="Force refetch data from Last.fm API"
          >
            🔄 Force Fetch
          </button>

          {/* Status */}
          {status && <div style={statusStyle}>{status}</div>}
        </div>
      </div>

      {/* Preview panel (right side, 50% width) */}
      <div style={previewContainerStyle}>
        <div>
          <h2 style={{ margin: '0 0 12px 0', fontSize: '14px', fontWeight: '600', color: '#aaa', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            Preview
          </h2>
        </div>
        <div style={previewBoxStyle}>
          {imageUrl ? (
            <img key={imageVersion} src={imageUrl} alt="report" style={{ maxWidth: '100%', maxHeight: '100%', borderRadius: '6px' }} />
          ) : (
            <span style={{ color: '#555', fontSize: '14px' }}>No preview yet</span>
          )}
        </div>
      </div>
    </div>
  );
}
